version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "dataService Cluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_RACK: "rack1"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool statusgossip && nodetool status | grep -E '^UN'"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend

  data-service:
    image: aluze/online-dataservice:latest
    container_name: data-service
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      SPRING_CASSANDRA_CONTACTPOINTS: cassandra
      SPRING_CASSANDRA_PORT: 9042
    networks:
      - backend
    restart: unless-stopped

  auth-db:
    image: postgres:13.1-alpine
    container_name: auth-db
    environment:
      POSTGRES_USER: online_users_db
      POSTGRES_PASSWORD: online_users_db
      POSTGRES_DB: online_users_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U online_users_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    image: aluze/online-authservice:latest
    container_name: auth-service
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/online_users_db
      SPRING_DATASOURCE_USERNAME: online_users_db
      SPRING_DATASOURCE_PASSWORD: online_users_db
    networks:
      - backend
    restart: unless-stopped

  group-service:
    image: aluze/online-groupservice:latest
    container_name: group-service
    networks:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - data-service
      - auth-service
      - group-service
    networks:
      - backend

volumes:
  cassandra_data:
  pg_data:

networks:
  backend:
    name: backend
    driver: bridge
    external: false