services:
  auth-service:
    extends:
      file: ./AuthService/docker/docker-compose.yaml
      service: auth-service
    networks:
      - backend

  auth-db:
    extends:
      file: ./AuthService/docker/docker-compose.yaml
      service: auth-db
    networks:
      - backend

  test:
    build: ./Test/docker
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - test
      - auth-service
    networks:
      - backend


networks:
  backend:
    name: backend
    external: false
    driver: bridge
