services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "dataService Cluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_SEEDS: "cassandra"
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

  dataservice:
    ports:
      - "8080:8080"
    depends_on:
      cassandra:
        condition: service_healthy
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        JAR_FILE: dataService.jar
    environment:
      SPRING_CASSANDRA_CONTACTPOINTS: cassandra
      SPRING_CASSANDRA_PORT: 9042
    restart: always

volumes:
  cassandra-data: